plugins {
    id("com.android.library") version "8.11.1"
    id("org.jetbrains.kotlin.android") version "2.0.21"
    id("org.jetbrains.kotlin.plugin.serialization") version "2.0.21"
    id("maven-publish")
    id("signing")
    id("io.github.gradle-nexus.publish-plugin") version "2.0.0"
}

// Import required for publishing task types  
import org.gradle.api.publish.maven.tasks.PublishToMavenRepository
import org.gradle.api.publish.tasks.GenerateModuleMetadata

// Function to extract version from Version.kt
fun getVersionFromKotlin(): String {
    val versionFile = file("src/main/kotlin/com/gr4vy/sdk/Version.kt")
    val versionRegex = """const val current = "(.+)"""".toRegex()
    val versionText = versionFile.readText()
    val matchResult = versionRegex.find(versionText)
    return matchResult?.groupValues?.get(1) ?: "1.0.0"
}

// Function to convert version string to version code
fun getVersionCode(version: String): Int {
    val parts = version.split("-")[0].split(".")
    if (parts.size >= 3) {
        val major = parts[0].toIntOrNull() ?: 0
        val minor = parts[1].toIntOrNull() ?: 0
        val patch = parts[2].toIntOrNull() ?: 0
        return major * 10000 + minor * 100 + patch
    }
    return 1
}

val sdkVersion = getVersionFromKotlin()

android {
    namespace = "com.gr4vy.sdk"
    compileSdk = 36
    
    // Disable automatic sources jar generation to avoid conflicts
    publishing {
        singleVariant("release") {
            // Don't publish sources automatically - we'll add them manually
        }
    }

    defaultConfig {
        minSdk = 26
        
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles("consumer-rules.pro")
        
        // Build configuration fields
        buildConfigField("String", "SDK_VERSION", "\"$sdkVersion\"")
        buildConfigField("boolean", "DEBUG_MODE", "false")
    }

    signingConfigs {
        create("release") {
            // For Android libraries, we use debug signing in development
            // The consuming app will handle the final production signing
            if (project.hasProperty("RELEASE_STORE_FILE")) {
                storeFile = file(project.property("RELEASE_STORE_FILE").toString())
                storePassword = project.property("RELEASE_STORE_PASSWORD").toString()
                keyAlias = project.property("RELEASE_KEY_ALIAS").toString()
                keyPassword = project.property("RELEASE_KEY_PASSWORD").toString()
            } else {
                // Fallback to debug signing for library development
                // This allows the library to be built and tested without production keys
                val debugKeystore = file("${System.getProperty("user.home")}/.android/debug.keystore")
                if (debugKeystore.exists()) {
                    storeFile = debugKeystore
                } else {
                    // If no debug keystore exists, create a temporary one for CI/CD
                    storeFile = file("${layout.buildDirectory.get()}/tmp/debug.keystore").apply {
                        if (!exists()) {
                            parentFile.mkdirs()
                            // This would be generated by CI/CD or development setup
                            println("Warning: Using temporary keystore for library development")
                        }
                    }
                }
                storePassword = "android"
                keyAlias = "androiddebugkey"
                keyPassword = "android"
            }
        }
    }

    buildTypes {
        debug {
            enableUnitTestCoverage = true
            buildConfigField("boolean", "DEBUG_MODE", "true")
            
            // Debug optimizations
            isMinifyEnabled = false
            isShrinkResources = false
            
            // Use default debug ProGuard rules for testing our ProGuard rules
            proguardFiles(getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro")
        }
        
        release {
            // Completely disable minification and ProGuard for SDK library
            isMinifyEnabled = false
            isShrinkResources = false
            
            // Remove ProGuard configuration to prevent any R8 optimizations
            // Consumer apps will handle their own optimization via consumer-rules.pro
            
            // Use release signing config
            signingConfig = signingConfigs.getByName("release")
            
            // Additional release optimizations
            buildConfigField("boolean", "DEBUG_MODE", "false")
        }
        
        create("benchmark") {
            initWith(getByName("release"))
            signingConfig = signingConfigs.getByName("debug")
            matchingFallbacks.add("release")
            // Note: isProfileable not available for library modules
        }
    }
    
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_11
        targetCompatibility = JavaVersion.VERSION_11
        
        // Enable incremental compilation
        isCoreLibraryDesugaringEnabled = false
    }
    
    kotlinOptions {
        jvmTarget = "11"
        
        // Kotlin compiler optimizations
        freeCompilerArgs += listOf(
            "-opt-in=kotlin.RequiresOptIn",
            "-Xjsr305=strict",
            "-Xuse-inline-scopes-numbers"
        )
    }

    // Enable build features
    buildFeatures {
        buildConfig = true
        resValues = false
        shaders = false
    }
    
    // Packaging options
    packaging {
        resources {
            excludes += listOf(
                "/META-INF/{AL2.0,LGPL2.1}",
                "/META-INF/DEPENDENCIES",
                "/META-INF/LICENSE",
                "/META-INF/LICENSE.txt",
                "/META-INF/license.txt",
                "/META-INF/NOTICE",
                "/META-INF/NOTICE.txt",
                "/META-INF/notice.txt",
                "/META-INF/ASL2.0",
                "/META-INF/*.kotlin_module"
            )
        }
    }
    
    // Test options
    testOptions {
        unitTests {
            isIncludeAndroidResources = true
            isReturnDefaultValues = true
            
            all { test ->
                test.testLogging {
                    events("passed", "skipped", "failed")
                    showStandardStreams = false
                }
            }
        }
    }
}

dependencies {
    // Kotlin
    implementation("org.jetbrains.kotlin:kotlin-stdlib:2.0.21")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3")
    
    // Serialization
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    
    // Networking
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    
    // Testing
    testImplementation("junit:junit:4.13.2")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.7.3")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.12.0")
    testImplementation("org.robolectric:robolectric:4.11.1")
    
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.6.1")
}

// Register custom tasks for Maven Central publishing 
val mavenSourcesJar by tasks.registering(Jar::class) {
    archiveClassifier.set("sources")
    from(android.sourceSets.getByName("main").java.srcDirs)
}

val mavenJavadocJar by tasks.registering(Jar::class) {
    archiveClassifier.set("javadoc")
    // Create empty javadoc jar to satisfy Maven Central requirements
    // Full javadoc generation can be complex for Android libraries
    val javadocDir = layout.buildDirectory.dir("tmp/javadoc")
    from(javadocDir)
    
    doFirst {
        javadocDir.get().asFile.mkdirs()
        javadocDir.get().file("README.txt").asFile.writeText(
            "This library uses Kotlin with inline documentation.\n" +
            "Please refer to the source code and GitHub repository for documentation."
        )
    }
}

publishing {
    publications {
        register<MavenPublication>("release") {
            groupId = "com.gr4vy"
            artifactId = "gr4vy-kotlin"
            version = sdkVersion

            afterEvaluate {
                from(components["release"])
            }
            
            // Required artifacts for Maven Central
            artifact(mavenSourcesJar)
            artifact(mavenJavadocJar)

            pom {
                name.set("Gr4vy Kotlin SDK")
                description.set("Official Kotlin SDK for Gr4vy payment processing")
                url.set("https://github.com/gr4vy/gr4vy-kotlin")
                
                licenses {
                    license {
                        name.set("MIT")
                        url.set("https://opensource.org/licenses/MIT")
                    }
                }
                
                developers {
                    developer {
                        id.set("gr4vy")
                        name.set("Gr4vy")
                        email.set("support@gr4vy.com")
                    }
                }
                
                scm {
                    connection.set("scm:git:git://github.com/gr4vy/gr4vy-kotlin.git")
                    developerConnection.set("scm:git:ssh://github.com:gr4vy/gr4vy-kotlin.git")
                    url.set("https://github.com/gr4vy/gr4vy-kotlin/tree/main")
                }
            }
        }
    }
}

// Ensure publishing tasks depend on artifact generation tasks
tasks.withType<PublishToMavenRepository>().configureEach {
    dependsOn(mavenSourcesJar)
    dependsOn(mavenJavadocJar)
}

tasks.withType<GenerateModuleMetadata>().configureEach {
    dependsOn(mavenSourcesJar)
    dependsOn(mavenJavadocJar)
}

// Signing configuration for Maven Central
signing {
    val signingKey: String? by project
    val signingPassword: String? by project
    
    // Only sign if keys are available (for CI/CD)
    if (signingKey != null && signingPassword != null) {
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign(publishing.publications["release"])
    }
}

// Nexus publishing configuration
nexusPublishing {
    repositories {
        sonatype {
            nexusUrl.set(uri("https://s01.oss.sonatype.org/service/local/"))
            snapshotRepositoryUrl.set(uri("https://s01.oss.sonatype.org/content/repositories/snapshots/"))
            username.set(project.findProperty("ossrhUsername") as String? ?: System.getenv("OSSRH_USERNAME"))
            password.set(project.findProperty("ossrhPassword") as String? ?: System.getenv("OSSRH_PASSWORD"))
            packageGroup.set("com.gr4vy") 
        }
    }
}

// Print the SDK version during build for verification
println("Gr4vy Kotlin SDK version: $sdkVersion")

// Coverage is handled by IntelliJ IDEA's built-in runner - no build configuration needed!
